---
dependencies:
- name: "activiti-cloud-query-graphql-query"
  repository: "https://introproventures.storage.googleapis.com"
  version: "1.0.55"
  alias: "graphql-query"
- name: "activiti-cloud-query-graphql-notifications"
  repository: "https://introproventures.storage.googleapis.com"
  version: "1.0.44"
  alias: "graphql-notifications"
- name: "activiti-cloud-query-graphql-subscriptions"
  repository: "https://introproventures.storage.googleapis.com"
  version: "1.0.41"
  alias: "graphql-subscriptions"
